Search.appendIndex(
    [
                {
            "fqsen": "\\Fzb\\AppException",
            "name": "AppException",
            "summary": "",
            "url": "classes/Fzb-AppException.html"
        },                {
            "fqsen": "\\Fzb\\App",
            "name": "App",
            "summary": "",
            "url": "classes/Fzb-App.html"
        },                {
            "fqsen": "\\Fzb\\AuthException",
            "name": "AuthException",
            "summary": "",
            "url": "classes/Fzb-AuthException.html"
        },                {
            "fqsen": "\\Fzb\\Auth",
            "name": "Auth",
            "summary": "",
            "url": "classes/Fzb-Auth.html"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Auth.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "interface\u0020for\u0020retrieving\u0020the\u0020Auth\u0020singleton",
            "url": "classes/Fzb-Auth.html#method_get_instance"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003Alogin\u0028\u0029",
            "name": "login",
            "summary": "Attempts\u0020to\u0020log\u0020in\u0020a\u0020user\u0020via\u0020username\/password.",
            "url": "classes/Fzb-Auth.html#method_login"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003Alogout\u0028\u0029",
            "name": "logout",
            "summary": "Logs\u0020a\u0020user\u0020out.\u0020\u0020Invalidates\u0020the\u0020user\u0020session\u0020and\u0020deletes\u0020the\u0020auth\u0020token\u0020cookie.",
            "url": "classes/Fzb-Auth.html#method_logout"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003Aon_failure\u0028\u0029",
            "name": "on_failure",
            "summary": "",
            "url": "classes/Fzb-Auth.html#method_on_failure"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A\u0024login_required",
            "name": "login_required",
            "summary": "",
            "url": "classes/Fzb-Auth.html#property_login_required"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003Acsrf_required\u0028\u0029",
            "name": "csrf_required",
            "summary": "",
            "url": "classes/Fzb-Auth.html#method_csrf_required"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A\u0024user",
            "name": "user",
            "summary": "",
            "url": "classes/Fzb-Auth.html#property_user"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A\u0024user_session",
            "name": "user_session",
            "summary": "",
            "url": "classes/Fzb-Auth.html#property_user_session"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A\u0024is_authenticated",
            "name": "is_authenticated",
            "summary": "",
            "url": "classes/Fzb-Auth.html#property_is_authenticated"
        },                {
            "fqsen": "\\Fzb\\Auth\u003A\u003A\u0024csrf_validated",
            "name": "csrf_validated",
            "summary": "",
            "url": "classes/Fzb-Auth.html#property_csrf_validated"
        },                {
            "fqsen": "\\Fzb\\Benchmark",
            "name": "Benchmark",
            "summary": "",
            "url": "classes/Fzb-Benchmark.html"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Benchmark.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003Astart\u0028\u0029",
            "name": "start",
            "summary": "Start\u0020Benchmarking",
            "url": "classes/Fzb-Benchmark.html#method_start"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003Aend\u0028\u0029",
            "name": "end",
            "summary": "End\u0020Benchmarking",
            "url": "classes/Fzb-Benchmark.html#method_end"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Print\u0020out\u0020Benchmark\u0020stats",
            "url": "classes/Fzb-Benchmark.html#method_show"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Fzb-Benchmark.html#property_name"
        },                {
            "fqsen": "\\Fzb\\Benchmark\u003A\u003A\u0024time_total",
            "name": "time_total",
            "summary": "",
            "url": "classes/Fzb-Benchmark.html#property_time_total"
        },                {
            "fqsen": "\\Fzb\\ConfigException",
            "name": "ConfigException",
            "summary": "",
            "url": "classes/Fzb-ConfigException.html"
        },                {
            "fqsen": "\\Fzb\\Config",
            "name": "Config",
            "summary": "",
            "url": "classes/Fzb-Config.html"
        },                {
            "fqsen": "\\Fzb\\Config\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Config.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Config\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "interface\u0020for\u0020retrieving\u0020the\u0020Config\u0020singleton",
            "url": "classes/Fzb-Config.html#method_get_instance"
        },                {
            "fqsen": "\\Fzb\\Config\u003A\u003Aget_settings\u0028\u0029",
            "name": "get_settings",
            "summary": "Gets\u0020a\u0020specified\u0020section\u0020from\u0020the\u0020config\u0020as\u0020an\u0020associative\u0020array",
            "url": "classes/Fzb-Config.html#method_get_settings"
        },                {
            "fqsen": "\\Fzb\\DatabaseException",
            "name": "DatabaseException",
            "summary": "",
            "url": "classes/Fzb-DatabaseException.html"
        },                {
            "fqsen": "\\Fzb\\Database",
            "name": "Database",
            "summary": "",
            "url": "classes/Fzb-Database.html"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Database.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Retrieves\u0020the\u0020default\u0020or\u0020specified\u0020instance",
            "url": "classes/Fzb-Database.html#method_get_instance"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aset_active_db\u0028\u0029",
            "name": "set_active_db",
            "summary": "Sets\u0020the\u0020active\u0020database\u0020instance.",
            "url": "classes/Fzb-Database.html#method_set_active_db"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "Connects\u0020to\u0020database\u0020using\u0020provided\u0020connection\u0020info",
            "url": "classes/Fzb-Database.html#method_connect"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Fzb-Database.html#method___destruct"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Adisconnect\u0028\u0029",
            "name": "disconnect",
            "summary": "Disconnects\u0020from\u0020the\u0020database",
            "url": "classes/Fzb-Database.html#method_disconnect"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aprepare\u0028\u0029",
            "name": "prepare",
            "summary": "Prepares\u0020a\u0020query\u0020statement",
            "url": "classes/Fzb-Database.html#method_prepare"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "Executes\u0020a\u0020prepared\u0020statement",
            "url": "classes/Fzb-Database.html#method_execute"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Afinish\u0028\u0029",
            "name": "finish",
            "summary": "Closes\u0020the\u0020current\u0020database\u0020cursor",
            "url": "classes/Fzb-Database.html#method_finish"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Afetchrow_array\u0028\u0029",
            "name": "fetchrow_array",
            "summary": "Fetches\u0020the\u0020result\u0020of\u0020an\u0020executed\u0020statement\u0020as\u0020a\u0020regular\u0020array\n\u0020\u0020\u0020\u0020\u0020\u002A",
            "url": "classes/Fzb-Database.html#method_fetchrow_array"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Afetchrow_assoc\u0028\u0029",
            "name": "fetchrow_assoc",
            "summary": "Fetches\u0020the\u0020result\u0020of\u0020an\u0020executed\u0020statement\u0020as\u0020an\u0020associative\u0020array",
            "url": "classes/Fzb-Database.html#method_fetchrow_assoc"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aquery\u0028\u0029",
            "name": "query",
            "summary": "Prepares\u0020and\u0020executes\u0020a\u0020query",
            "url": "classes/Fzb-Database.html#method_query"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aselectrow_array\u0028\u0029",
            "name": "selectrow_array",
            "summary": "Executes\u0020a\u0020query\u0020and\u0020returns\u0020the\u0020first\u0020row\u0020of\u0020the\u0020result\u0020as\u0020a\u0020normal\u0020array",
            "url": "classes/Fzb-Database.html#method_selectrow_array"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aselectrow_assoc\u0028\u0029",
            "name": "selectrow_assoc",
            "summary": "Executes\u0020a\u0020query\u0020and\u0020returns\u0020the\u0020first\u0020row\u0020of\u0020the\u0020result\u0020as\u0020an\u0020associative\u0020array",
            "url": "classes/Fzb-Database.html#method_selectrow_assoc"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aselectcol_array\u0028\u0029",
            "name": "selectcol_array",
            "summary": "Execues\u0020a\u0020query\u0020and\u0020returns\u0020the\u0020first\u0020column\u0020of\u0020each\u0020row",
            "url": "classes/Fzb-Database.html#method_selectcol_array"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aselectall_array\u0028\u0029",
            "name": "selectall_array",
            "summary": "Execues\u0020a\u0020query\u0020and\u0020returns\u0020the\u0020first\u0020column\u0020of\u0020each\u0020row",
            "url": "classes/Fzb-Database.html#method_selectall_array"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Alast_insert_id\u0028\u0029",
            "name": "last_insert_id",
            "summary": "Last\u0020insert\u0020ID",
            "url": "classes/Fzb-Database.html#method_last_insert_id"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Abegin_transaction\u0028\u0029",
            "name": "begin_transaction",
            "summary": "Begin\u0020transatction",
            "url": "classes/Fzb-Database.html#method_begin_transaction"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Acommit\u0028\u0029",
            "name": "commit",
            "summary": "Commits\u0020a\u0020transaction",
            "url": "classes/Fzb-Database.html#method_commit"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aauto_insert_update\u0028\u0029",
            "name": "auto_insert_update",
            "summary": "A\u0020query\u0020builder\u0020which\u0020attempts\u0020to\u0020insert\u0020or\u0020update\u0020data\u0020into\u0020a\u0020specified\u0020table\u0020based\u0020on\nprovided\u0020primary\u0020key\u0020and\u0020primary\u0020key\u0020value.",
            "url": "classes/Fzb-Database.html#method_auto_insert_update"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aget_column_names\u0028\u0029",
            "name": "get_column_names",
            "summary": "Gets\u0020the\u0020column\u0020names\u0020of\u0020a\u0020specified\u0020table",
            "url": "classes/Fzb-Database.html#method_get_column_names"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aget_table_schema\u0028\u0029",
            "name": "get_table_schema",
            "summary": "Gets\u0020the\u0020schema\u0020of\u0020a\u0020specified\u0020table",
            "url": "classes/Fzb-Database.html#method_get_table_schema"
        },                {
            "fqsen": "\\Fzb\\Database\u003A\u003Aget_tables\u0028\u0029",
            "name": "get_tables",
            "summary": "Gets\u0020a\u0020list\u0020of\u0020tables\u0020in\u0020the\u0020current\u0020database",
            "url": "classes/Fzb-Database.html#method_get_tables"
        },                {
            "fqsen": "\\Fzb\\HtmxException",
            "name": "HtmxException",
            "summary": "",
            "url": "classes/Fzb-HtmxException.html"
        },                {
            "fqsen": "\\Fzb\\Htmx",
            "name": "Htmx",
            "summary": "",
            "url": "classes/Fzb-Htmx.html"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Ais_boosted\u0028\u0029",
            "name": "is_boosted",
            "summary": "Indicates\u0020that\u0020the\u0020request\u0020is\u0020via\u0020an\u0020element\u0020using\u0020hx\u002Dboost",
            "url": "classes/Fzb-Htmx.html#method_is_boosted"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Acurrent_url\u0028\u0029",
            "name": "current_url",
            "summary": "The\u0020current\u0020URL\u0020of\u0020the\u0020browser",
            "url": "classes/Fzb-Htmx.html#method_current_url"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Ais_history_restore_request\u0028\u0029",
            "name": "is_history_restore_request",
            "summary": "Returns\u0020\u201Ctrue\u201D\u0020if\u0020the\u0020request\u0020is\u0020for\u0020history\u0020restoration\u0020after\u0020a\u0020miss\u0020in\u0020the\u0020local\u0020history\u0020cache",
            "url": "classes/Fzb-Htmx.html#method_is_history_restore_request"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Aprompt\u0028\u0029",
            "name": "prompt",
            "summary": "The\u0020user\u0020response\u0020to\u0020an\u0020hx\u002Dprompt",
            "url": "classes/Fzb-Htmx.html#method_prompt"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Ais_htmx_request\u0028\u0029",
            "name": "is_htmx_request",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020request\u0020was\u0020from\u0020htmx",
            "url": "classes/Fzb-Htmx.html#method_is_htmx_request"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atarget_id\u0028\u0029",
            "name": "target_id",
            "summary": "Returns\u0020the\u0020id\u0020of\u0020the\u0020target\u0020element\u0020if\u0020it\u0020exists",
            "url": "classes/Fzb-Htmx.html#method_target_id"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atriggered_name\u0028\u0029",
            "name": "triggered_name",
            "summary": "Returns\u0020the\u0020name\u0020of\u0020the\u0020triggered\u0020element\u0020if\u0020it\u0020exists",
            "url": "classes/Fzb-Htmx.html#method_triggered_name"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atriggered_id\u0028\u0029",
            "name": "triggered_id",
            "summary": "Returns\u0020the\u0020id\u0020of\u0020the\u0020triggered\u0020element\u0020if\u0020it\u0020exists",
            "url": "classes/Fzb-Htmx.html#method_triggered_id"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Alocation\u0028\u0029",
            "name": "location",
            "summary": "Allows\u0020you\u0020to\u0020do\u0020a\u0020client\u002Dside\u0020redirect\u0020that\u0020does\u0020not\u0020do\u0020a\u0020full\u0020page\u0020reload",
            "url": "classes/Fzb-Htmx.html#method_location"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Apush_url\u0028\u0029",
            "name": "push_url",
            "summary": "Pushes\u0020a\u0020new\u0020url\u0020into\u0020the\u0020history\u0020stack",
            "url": "classes/Fzb-Htmx.html#method_push_url"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Can\u0020be\u0020used\u0020to\u0020do\u0020a\u0020client\u002Dside\u0020redirect\u0020to\u0020a\u0020new\u0020location",
            "url": "classes/Fzb-Htmx.html#method_redirect"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Arefresh\u0028\u0029",
            "name": "refresh",
            "summary": "Triggers\u0020the\u0020client\u002Dside\u0020to\u0020do\u0020a\u0020full\u0020refresh\u0020of\u0020the\u0020page",
            "url": "classes/Fzb-Htmx.html#method_refresh"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Areplace_url\u0028\u0029",
            "name": "replace_url",
            "summary": "Replaces\u0020the\u0020current\u0020URL\u0020in\u0020the\u0020location\u0020bar",
            "url": "classes/Fzb-Htmx.html#method_replace_url"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Areswap\u0028\u0029",
            "name": "reswap",
            "summary": "Allows\u0020you\u0020to\u0020specify\u0020how\u0020the\u0020response\u0020will\u0020be\u0020swapped.",
            "url": "classes/Fzb-Htmx.html#method_reswap"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Aretarget\u0028\u0029",
            "name": "retarget",
            "summary": "Updates\u0020the\u0020target\u0020of\u0020the\u0020content\u0020update\u0020to\u0020a\u0020different\u0020element\u0020on\u0020the\u0020page",
            "url": "classes/Fzb-Htmx.html#method_retarget"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Areselect\u0028\u0029",
            "name": "reselect",
            "summary": "Overrides\u0020an\u0020existing\u0020hx\u002Dselect\u0020on\u0020the\u0020triggering\u0020element.",
            "url": "classes/Fzb-Htmx.html#method_reselect"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atrigger\u0028\u0029",
            "name": "trigger",
            "summary": "Allows\u0020you\u0020to\u0020trigger\u0020client\u002Dside\u0020events",
            "url": "classes/Fzb-Htmx.html#method_trigger"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atrigger_after_settle\u0028\u0029",
            "name": "trigger_after_settle",
            "summary": "Allows\u0020you\u0020to\u0020trigger\u0020client\u002Dside\u0020events\u0020after\u0020the\u0020settle\u0020step",
            "url": "classes/Fzb-Htmx.html#method_trigger_after_settle"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Atrigger_after_swap\u0028\u0029",
            "name": "trigger_after_swap",
            "summary": "Allows\u0020you\u0020to\u0020trigger\u0020client\u002Dside\u0020events\u0020after\u0020the\u0020swap\u0020step",
            "url": "classes/Fzb-Htmx.html#method_trigger_after_swap"
        },                {
            "fqsen": "\\Fzb\\Htmx\u003A\u003Ano_content\u0028\u0029",
            "name": "no_content",
            "summary": "Send\u0020no\u0020content,\u0020for\u0020triggering\u0020client\u0020side\u0020events\u0020only",
            "url": "classes/Fzb-Htmx.html#method_no_content"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap",
            "name": "HtmxSwap",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003AinnerHTML",
            "name": "innerHTML",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_innerHTML"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003AouterHTML",
            "name": "outerHTML",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_outerHTML"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Abeforebegin",
            "name": "beforebegin",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_beforebegin"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Aafterbegin",
            "name": "afterbegin",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_afterbegin"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Abeforeend",
            "name": "beforeend",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_beforeend"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Aafterend",
            "name": "afterend",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_afterend"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Adelete",
            "name": "delete",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_delete"
        },                {
            "fqsen": "\\Fzb\\HtmxSwap\u003A\u003Anone",
            "name": "none",
            "summary": "",
            "url": "classes/Fzb-HtmxSwap.html#enumcase_none"
        },                {
            "fqsen": "\\Fzb\\InputException",
            "name": "InputException",
            "summary": "",
            "url": "classes/Fzb-InputException.html"
        },                {
            "fqsen": "\\Fzb\\Input",
            "name": "Input",
            "summary": "",
            "url": "classes/Fzb-Input.html"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Input.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Afrom_request\u0028\u0029",
            "name": "from_request",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_from_request"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_missing\u0028\u0029",
            "name": "is_missing",
            "summary": "Checks\u0020if\u0020any\u0020required\u0020field\u0020is\u0020missing",
            "url": "classes/Fzb-Input.html#method_is_missing"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_invalid\u0028\u0029",
            "name": "is_invalid",
            "summary": "Checks\u0020if\u0020any\u0020validated\u0020field\u0020is\u0020invalid",
            "url": "classes/Fzb-Input.html#method_is_invalid"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Arequest_method\u0028\u0029",
            "name": "request_method",
            "summary": "Request\u0020method\u0020checking\n\u0020\u0020Wrappers\u0020for\u0020\u0024_SERVER\u005B\u0027REQUEST_METHOD\u0027\u005D",
            "url": "classes/Fzb-Input.html#method_request_method"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_post\u0028\u0029",
            "name": "is_post",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_is_post"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_get\u0028\u0029",
            "name": "is_get",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_is_get"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_put\u0028\u0029",
            "name": "is_put",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_is_put"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Ais_delete\u0028\u0029",
            "name": "is_delete",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_is_delete"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "ArrayAccess\u0020methods",
            "url": "classes/Fzb-Input.html#method_offsetSet"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_offsetExists"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_offsetUnset"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_offsetGet"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Iterator\u0020methods",
            "url": "classes/Fzb-Input.html#method_current"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_key"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_next"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_rewind"
        },                {
            "fqsen": "\\Fzb\\Input\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/Fzb-Input.html#method_valid"
        },                {
            "fqsen": "\\Fzb\\InputObject",
            "name": "InputObject",
            "summary": "InputObject\u0020Class",
            "url": "classes/Fzb-InputObject.html"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#method___toString"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#property_value"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A\u0024submitted_value",
            "name": "submitted_value",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#property_submitted_value"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A\u0024is_required",
            "name": "is_required",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#property_is_required"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A\u0024is_missing",
            "name": "is_missing",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#property_is_missing"
        },                {
            "fqsen": "\\Fzb\\InputObject\u003A\u003A\u0024is_invalid",
            "name": "is_invalid",
            "summary": "",
            "url": "classes/Fzb-InputObject.html#property_is_invalid"
        },                {
            "fqsen": "\\Fzb\\ModelException",
            "name": "ModelException",
            "summary": "",
            "url": "classes/Fzb-ModelException.html"
        },                {
            "fqsen": "\\Fzb\\Model",
            "name": "Model",
            "summary": "",
            "url": "classes/Fzb-Model.html"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Model.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Adb\u0028\u0029",
            "name": "db",
            "summary": "Gets\u0020the\u0020current\u0020Database\u0020object",
            "url": "classes/Fzb-Model.html#method_db"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saves\u0020the\u0020model\u0027s\u0020current\u0020data\u0020to\u0020the\u0020database",
            "url": "classes/Fzb-Model.html#method_save"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aload\u0028\u0029",
            "name": "load",
            "summary": "Loads\u0020a\u0020model\u0027s\u0020data\u0020from\u0020the\u0020database",
            "url": "classes/Fzb-Model.html#method_load"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_delete"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aget_all\u0028\u0029",
            "name": "get_all",
            "summary": "Gets\u0020all\u0020model\u0020objects\u0020stored\u0020in\u0020DB",
            "url": "classes/Fzb-Model.html#method_get_all"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aget_by\u0028\u0029",
            "name": "get_by",
            "summary": "Gets\u0020model\u0020objects\u0020by\u0020where\u0020..\u0020and\u0020clause\u0020of\u0020specified\u0020parameters",
            "url": "classes/Fzb-Model.html#method_get_by"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aget_count\u0028\u0029",
            "name": "get_count",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_get_count"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aget_count_by\u0028\u0029",
            "name": "get_count_by",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_get_count_by"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Afrom_sql\u0028\u0029",
            "name": "from_sql",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_from_sql"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aget_sql_fields\u0028\u0029",
            "name": "get_sql_fields",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_get_sql_fields"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003Aselect_fields\u0028\u0029",
            "name": "select_fields",
            "summary": "",
            "url": "classes/Fzb-Model.html#method_select_fields"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A__primary_key__",
            "name": "__primary_key__",
            "summary": "",
            "url": "classes/Fzb-Model.html#constant___primary_key__"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A__table__",
            "name": "__table__",
            "summary": "",
            "url": "classes/Fzb-Model.html#constant___table__"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Fzb-Model.html#property_id"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A\u0024created_at",
            "name": "created_at",
            "summary": "",
            "url": "classes/Fzb-Model.html#property_created_at"
        },                {
            "fqsen": "\\Fzb\\Model\u003A\u003A\u0024updated_at",
            "name": "updated_at",
            "summary": "",
            "url": "classes/Fzb-Model.html#property_updated_at"
        },                {
            "fqsen": "\\Fzb\\RedisException",
            "name": "RedisException",
            "summary": "",
            "url": "classes/Fzb-RedisException.html"
        },                {
            "fqsen": "\\Fzb\\Redis",
            "name": "Redis",
            "summary": "",
            "url": "classes/Fzb-Redis.html"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Redis.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "Destructor",
            "url": "classes/Fzb-Redis.html#method___destruct"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "Retrieves\u0020the\u0020default\u0020or\u0020specified\u0020instance",
            "url": "classes/Fzb-Redis.html#method_get_instance"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Aconnect\u0028\u0029",
            "name": "connect",
            "summary": "",
            "url": "classes/Fzb-Redis.html#method_connect"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Adisconnect\u0028\u0029",
            "name": "disconnect",
            "summary": "Disconnects\u0020from\u0020the\u0020Redis\u0020server",
            "url": "classes/Fzb-Redis.html#method_disconnect"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Atest\u0028\u0029",
            "name": "test",
            "summary": "tests\u0020a\u0020connection\u0020using\u0020the\u0020Redis\u0020PING\u0020command",
            "url": "classes/Fzb-Redis.html#method_test"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Acmd\u0028\u0029",
            "name": "cmd",
            "summary": "Executes\u0020a\u0020Redis\u0020command\u0020and\u0020returns\u0020the\u0020response",
            "url": "classes/Fzb-Redis.html#method_cmd"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Aparse_response\u0028\u0029",
            "name": "parse_response",
            "summary": "Parses\u0020a\u0020response\u0020from\u0020the\u0020server\u0020into\u0020a\u0020PHP\u0020data\u0020structure\nCalls\u0020itself\u0020recursively\u0020to\u0020handle\u0020nested\u0020arrays",
            "url": "classes/Fzb-Redis.html#method_parse_response"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Sets\u0020a\u0020key\u0020to\u0020a\u0020value",
            "url": "classes/Fzb-Redis.html#method_set"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Gets\u0020a\u0020specified\u0020key",
            "url": "classes/Fzb-Redis.html#method_get"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahset\u0028\u0029",
            "name": "hset",
            "summary": "Wrapper\u0020for\u0020Redis\u0020HSET\u0020using\u0020PHP\u0020arrays",
            "url": "classes/Fzb-Redis.html#method_hset"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahget\u0028\u0029",
            "name": "hget",
            "summary": "Wrapper\u0020for\u0020Redis\u0020HGET",
            "url": "classes/Fzb-Redis.html#method_hget"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahgetall\u0028\u0029",
            "name": "hgetall",
            "summary": "Wrapper\u0020for\u0020Redis\u0020HGETALL",
            "url": "classes/Fzb-Redis.html#method_hgetall"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahkeys\u0028\u0029",
            "name": "hkeys",
            "summary": "Wrapper\u0020for\u0020Redis\u0020HKEYS",
            "url": "classes/Fzb-Redis.html#method_hkeys"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahdel\u0028\u0029",
            "name": "hdel",
            "summary": "Wrapper\u0020for\u0020Redis\u0020HDEL",
            "url": "classes/Fzb-Redis.html#method_hdel"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003Ahdelall\u0028\u0029",
            "name": "hdelall",
            "summary": "Deletes\u0020all\u0020fields\u0020from\u0020a\u0020Redis\u0020hash",
            "url": "classes/Fzb-Redis.html#method_hdelall"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003AREDIS_PORT",
            "name": "REDIS_PORT",
            "summary": "",
            "url": "classes/Fzb-Redis.html#constant_REDIS_PORT"
        },                {
            "fqsen": "\\Fzb\\Redis\u003A\u003ACHUNK_SIZE",
            "name": "CHUNK_SIZE",
            "summary": "",
            "url": "classes/Fzb-Redis.html#constant_CHUNK_SIZE"
        },                {
            "fqsen": "\\Fzb\\RedisError",
            "name": "RedisError",
            "summary": "RedisError\u0020Class",
            "url": "classes/Fzb-RedisError.html"
        },                {
            "fqsen": "\\Fzb\\RedisError\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Fzb-RedisError.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\RedisError\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Fzb-RedisError.html#method___toString"
        },                {
            "fqsen": "\\Fzb\\_load_tpl\u0028\u0029",
            "name": "_load_tpl",
            "summary": "Helper\u0020function\u0020to\u0020isolate\u0020the\u0020template\u0020scope\u0020from\u0020the\u0020rest\u0020of\u0020the\u0020class",
            "url": "namespaces/fzb.html#function__load_tpl"
        },                {
            "fqsen": "\\Fzb\\extend\u0028\u0029",
            "name": "extend",
            "summary": "",
            "url": "namespaces/fzb.html#function_extend"
        },                {
            "fqsen": "\\Fzb\\RendererException",
            "name": "RendererException",
            "summary": "",
            "url": "classes/Fzb-RendererException.html"
        },                {
            "fqsen": "\\Fzb\\Renderer",
            "name": "Renderer",
            "summary": "",
            "url": "classes/Fzb-Renderer.html"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-Renderer.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Aset\u0028\u0029",
            "name": "set",
            "summary": "Assigns\u0020data\u0020to\u0020the\u0020renderer\u0020as\u0020a\u0020render\u0020var",
            "url": "classes/Fzb-Renderer.html#method_set"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Aflag_error\u0028\u0029",
            "name": "flag_error",
            "summary": "",
            "url": "classes/Fzb-Renderer.html#method_flag_error"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Aset_all\u0028\u0029",
            "name": "set_all",
            "summary": "Flattens\u0020an\u0020associative\u0020array\u0020and\u0020assigns\u0020to\u0020render\u0020vars\u0020with\u0020key\u0020name\u0020as\u0020var\u0020name",
            "url": "classes/Fzb-Renderer.html#method_set_all"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Ashow\u0028\u0029",
            "name": "show",
            "summary": "Renders\u0020and\u0020displays\u0020a\u0020specified\u0020page",
            "url": "classes/Fzb-Renderer.html#method_show"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Arender_as_string\u0028\u0029",
            "name": "render_as_string",
            "summary": "Renders\u0020the\u0020template\u0020and\u0020returns\u0020output\u0020as\u0020a\u0020string\u0020instead\u0020of\u0020sending\u0020to\u0020the\u0020browser",
            "url": "classes/Fzb-Renderer.html#method_render_as_string"
        },                {
            "fqsen": "\\Fzb\\Renderer\u003A\u003Aredirect\u0028\u0029",
            "name": "redirect",
            "summary": "Send\u0020HTTP\u0020redirect\u0020header\nApplication\u0020should\u0020not\u0020send\u0020any\u0020more\u0020output\u0020to\u0020the\u0020browser\u0020after\u0020calling",
            "url": "classes/Fzb-Renderer.html#method_redirect"
        },                {
            "fqsen": "\\Fzb\\_htmlspecialchars\u0028\u0029",
            "name": "_htmlspecialchars",
            "summary": "Wrapper\u0020for\u0020htmlspecialchars\u0020to\u0020support\u0020arrays\u0020and\u0020objects",
            "url": "namespaces/fzb.html#function__htmlspecialchars"
        },                {
            "fqsen": "\\Fzb\\RenderVar",
            "name": "RenderVar",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-RenderVar.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003A__get\u0028\u0029",
            "name": "__get",
            "summary": "Returns\u0020a\u0020output\u0020for\u0020a\u0020stored\u0020object",
            "url": "classes/Fzb-RenderVar.html#method___get"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "HTML\u002Dsafe\u0020output\u0020gette",
            "url": "classes/Fzb-RenderVar.html#method___toString"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003A__call\u0028\u0029",
            "name": "__call",
            "summary": "Calls\u0020class\u0020method\u0020and\u0020gets\u0020HTML\u002Dsafe\u0020output",
            "url": "classes/Fzb-RenderVar.html#method___call"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003AoffsetSet\u0028\u0029",
            "name": "offsetSet",
            "summary": "Array\u0020Access\u0020Methods",
            "url": "classes/Fzb-RenderVar.html#method_offsetSet"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003AoffsetExists\u0028\u0029",
            "name": "offsetExists",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_offsetExists"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003AoffsetUnset\u0028\u0029",
            "name": "offsetUnset",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_offsetUnset"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003AoffsetGet\u0028\u0029",
            "name": "offsetGet",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_offsetGet"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003Acurrent\u0028\u0029",
            "name": "current",
            "summary": "Iterator\u0020Methods",
            "url": "classes/Fzb-RenderVar.html#method_current"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003Akey\u0028\u0029",
            "name": "key",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_key"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_next"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_rewind"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#method_valid"
        },                {
            "fqsen": "\\Fzb\\RenderVar\u003A\u003A\u0024unsafe",
            "name": "unsafe",
            "summary": "",
            "url": "classes/Fzb-RenderVar.html#property_unsafe"
        },                {
            "fqsen": "\\Fzb\\RouterException",
            "name": "RouterException",
            "summary": "",
            "url": "classes/Fzb-RouterException.html"
        },                {
            "fqsen": "\\Fzb\\Router",
            "name": "Router",
            "summary": "",
            "url": "classes/Fzb-Router.html"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor,\u0020implements\u0020singleton\u0020pattern",
            "url": "classes/Fzb-Router.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Fzb-Router.html#method___destruct"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_instance\u0028\u0029",
            "name": "get_instance",
            "summary": "interface\u0020for\u0020retrieving\u0020the\u0020Router\u0020singleton",
            "url": "classes/Fzb-Router.html#method_get_instance"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Acontroller_exists\u0028\u0029",
            "name": "controller_exists",
            "summary": "Identifies\u0020if\u0020a\u0020controller\u0020exists\u0020for\u0020the\u0020requested\u0020URI\u0020path",
            "url": "classes/Fzb-Router.html#method_controller_exists"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_controller\u0028\u0029",
            "name": "get_controller",
            "summary": "Returns\u0020path\u0020to\u0020the\u0020proper\u0020controller\u0020based\u0020on\u0020uri\u0020path",
            "url": "classes/Fzb-Router.html#method_get_controller"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_controller_path\u0028\u0029",
            "name": "get_controller_path",
            "summary": "GEts\u0020the\u0020URI\u0020path\u0020of\u0020the\u0020current\u0020controller",
            "url": "classes/Fzb-Router.html#method_get_controller_path"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_all_controllers\u0028\u0029",
            "name": "get_all_controllers",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_get_all_controllers"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Adetermine_route_path\u0028\u0029",
            "name": "determine_route_path",
            "summary": "Gets\u0020the\u0020route\u0020path\u0020relative\u0020to\u0020the\u0020root\u0020directory\u0020of\u0020the\u0020application\nAllows\u0020for\u0020the\u0020app\u0020to\u0020be\u0020in\u0020the\u0020document\u0020root\u0020or\u0020a\u0020subfolder",
            "url": "classes/Fzb-Router.html#method_determine_route_path"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aadd\u0028\u0029",
            "name": "add",
            "summary": "Adds\u0020a\u0020new\u0020route\u0020to\u0020the\u0020router",
            "url": "classes/Fzb-Router.html#method_add"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Alias\u0020for\u0020add\u0020method\u0020for\u0020GET\u0020endpoints",
            "url": "classes/Fzb-Router.html#method_get"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Apost\u0028\u0029",
            "name": "post",
            "summary": "Alias\u0020for\u0020add\u0020method\u0020for\u0020POST\u0020endpoints",
            "url": "classes/Fzb-Router.html#method_post"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Alias\u0020for\u0020add\u0020method\u0020for\u0020PUT\u0020endpoints",
            "url": "classes/Fzb-Router.html#method_put"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "Alias\u0020for\u0020add\u0020method\u0020for\u0020DELETE\u0020endpoints",
            "url": "classes/Fzb-Router.html#method_delete"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aroute\u0028\u0029",
            "name": "route",
            "summary": "Routes\u0020to\u0020the\u0020endpoint\u0020specified\u0020in\u0020the\u0020request\u0020URI\u0020path",
            "url": "classes/Fzb-Router.html#method_route"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ause_prefix\u0028\u0029",
            "name": "use_prefix",
            "summary": "Allows\u0020a\u0020prefix\u0020to\u0020be\u0020used\u0020for\u0020all\u0020endpoints\u0020after\u0020calling",
            "url": "classes/Fzb-Router.html#method_use_prefix"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ause_controller_prefix\u0028\u0029",
            "name": "use_controller_prefix",
            "summary": "Alias\u0020for\u0020use_prefix\u0028\u0029\u0020that\u0020uses\u0020the\u0020specified\u0020controller\u0020as\u0020the\u0020route\u0020prefix",
            "url": "classes/Fzb-Router.html#method_use_controller_prefix"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_app_base_path\u0028\u0029",
            "name": "get_app_base_path",
            "summary": "Gets\u0020the\u0020pase\u0020path\u0020of\u0020the\u0020application.\u0020For\u0020use\u0020when\u0020application\u0020is\u0020in\u0020a\u0020subdirectory\u0020of\u0020the\u0020webroot",
            "url": "classes/Fzb-Router.html#method_get_app_base_path"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_route\u0028\u0029",
            "name": "get_route",
            "summary": "Returns\u0020the\u0020current\u0020route",
            "url": "classes/Fzb-Router.html#method_get_route"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_routes\u0028\u0029",
            "name": "get_routes",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_get_routes"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Aget_path_vars\u0028\u0029",
            "name": "get_path_vars",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_get_path_vars"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Arequest_method\u0028\u0029",
            "name": "request_method",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_request_method"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ais_post\u0028\u0029",
            "name": "is_post",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_is_post"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ais_get\u0028\u0029",
            "name": "is_get",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_is_get"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ais_put\u0028\u0029",
            "name": "is_put",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_is_put"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Ais_delete\u0028\u0029",
            "name": "is_delete",
            "summary": "",
            "url": "classes/Fzb-Router.html#method_is_delete"
        },                {
            "fqsen": "\\Fzb\\Router\u003A\u003Avariable_regex",
            "name": "variable_regex",
            "summary": "",
            "url": "classes/Fzb-Router.html#constant_variable_regex"
        },                {
            "fqsen": "\\Fzb\\SMS2FAException",
            "name": "SMS2FAException",
            "summary": "",
            "url": "classes/Fzb-SMS2FAException.html"
        },                {
            "fqsen": "\\Fzb\\SMS2FA",
            "name": "SMS2FA",
            "summary": "",
            "url": "classes/Fzb-SMS2FA.html"
        },                {
            "fqsen": "\\Fzb\\SMS2FA\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Fzb-SMS2FA.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\SMS2FA\u003A\u003Agenerate_code\u0028\u0029",
            "name": "generate_code",
            "summary": "",
            "url": "classes/Fzb-SMS2FA.html#method_generate_code"
        },                {
            "fqsen": "\\Fzb\\SMS2FA\u003A\u003Avalidate_code\u0028\u0029",
            "name": "validate_code",
            "summary": "",
            "url": "classes/Fzb-SMS2FA.html#method_validate_code"
        },                {
            "fqsen": "\\Fzb\\SMS2FA\u003A\u003Asend_code\u0028\u0029",
            "name": "send_code",
            "summary": "",
            "url": "classes/Fzb-SMS2FA.html#method_send_code"
        },                {
            "fqsen": "\\Fzb\\SSEException",
            "name": "SSEException",
            "summary": "",
            "url": "classes/Fzb-SSEException.html"
        },                {
            "fqsen": "\\Fzb\\SSE",
            "name": "SSE",
            "summary": "",
            "url": "classes/Fzb-SSE.html"
        },                {
            "fqsen": "\\Fzb\\SSE\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-SSE.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\SSE\u003A\u003Amessage\u0028\u0029",
            "name": "message",
            "summary": "",
            "url": "classes/Fzb-SSE.html#method_message"
        },                {
            "fqsen": "\\Fzb\\TOTPException",
            "name": "TOTPException",
            "summary": "",
            "url": "classes/Fzb-TOTPException.html"
        },                {
            "fqsen": "\\Fzb\\TOTP",
            "name": "TOTP",
            "summary": "",
            "url": "classes/Fzb-TOTP.html"
        },                {
            "fqsen": "\\Fzb\\TOTP\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Fzb-TOTP.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\TOTP\u003A\u003Aget_code\u0028\u0029",
            "name": "get_code",
            "summary": "",
            "url": "classes/Fzb-TOTP.html#method_get_code"
        },                {
            "fqsen": "\\Fzb\\TOTP\u003A\u003Avalidate_code\u0028\u0029",
            "name": "validate_code",
            "summary": "",
            "url": "classes/Fzb-TOTP.html#method_validate_code"
        },                {
            "fqsen": "\\Fzb\\TOTP\u003A\u003Agenerate_secret\u0028\u0029",
            "name": "generate_secret",
            "summary": "",
            "url": "classes/Fzb-TOTP.html#method_generate_secret"
        },                {
            "fqsen": "\\Fzb\\UserException",
            "name": "UserException",
            "summary": "",
            "url": "classes/Fzb-UserException.html"
        },                {
            "fqsen": "\\Fzb\\User",
            "name": "User",
            "summary": "",
            "url": "classes/Fzb-User.html"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-User.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003Achange_password\u0028\u0029",
            "name": "change_password",
            "summary": "",
            "url": "classes/Fzb-User.html#method_change_password"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003Averify_password\u0028\u0029",
            "name": "verify_password",
            "summary": "",
            "url": "classes/Fzb-User.html#method_verify_password"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003A__table__",
            "name": "__table__",
            "summary": "",
            "url": "classes/Fzb-User.html#constant___table__"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003A\u0024username",
            "name": "username",
            "summary": "",
            "url": "classes/Fzb-User.html#property_username"
        },                {
            "fqsen": "\\Fzb\\User\u003A\u003A\u0024password",
            "name": "password",
            "summary": "",
            "url": "classes/Fzb-User.html#property_password"
        },                {
            "fqsen": "\\Fzb\\UserSessionException",
            "name": "UserSessionException",
            "summary": "",
            "url": "classes/Fzb-UserSessionException.html"
        },                {
            "fqsen": "\\Fzb\\UserSession",
            "name": "UserSession",
            "summary": "",
            "url": "classes/Fzb-UserSession.html"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fzb-UserSession.html#method___construct"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003Agenerate_uuid\u0028\u0029",
            "name": "generate_uuid",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#method_generate_uuid"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003Agenerate_fingerprint\u0028\u0029",
            "name": "generate_fingerprint",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#method_generate_fingerprint"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003Avalidate_fingerprint\u0028\u0029",
            "name": "validate_fingerprint",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#method_validate_fingerprint"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A__table__",
            "name": "__table__",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#constant___table__"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024user_id",
            "name": "user_id",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_user_id"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024logged_in",
            "name": "logged_in",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_logged_in"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024auth_token",
            "name": "auth_token",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_auth_token"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024csrf_token",
            "name": "csrf_token",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_csrf_token"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024fingerprint",
            "name": "fingerprint",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_fingerprint"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024sms_2fa_code",
            "name": "sms_2fa_code",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_sms_2fa_code"
        },                {
            "fqsen": "\\Fzb\\UserSession\u003A\u003A\u0024sms_2fa_expires_at",
            "name": "sms_2fa_expires_at",
            "summary": "",
            "url": "classes/Fzb-UserSession.html#property_sms_2fa_expires_at"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Fzb",
            "name": "Fzb",
            "summary": "",
            "url": "namespaces/fzb.html"
        }            ]
);
