name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: php-actions/composer@v6
      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        with:
          version: 12.4.1
          configuration: phpunit.xml