name: Build and Deploy PHPDoc

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Download phpDocumentor
        run: |
          curl -L https://phpdoc.org/phpDocumentor.phar -o phpDocumentor.phar
          chmod +x phpDocumentor.phar

      - name: Generate Documentation
        run: php phpDocumentor.phar --config=.phpdoc.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/phpdoc